title: LING-351-python-tutorial
author:
  name:  Hakyung Sung
  email: hksung001@gmail.com

# Theme and plugins
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]
  
# Minima-specific settings (v3+)
minima:
  # Pages to show in the nav, in the order listed
  nav_pages:
    - "0.md"

  # Date format (e.g. Jul-18-2025)
  date_format: "%b-%d-%Y"

  # Homepage excerpt toggle
  show_excerpts: false

  # Choose a skin: classic, dark, auto, solarized-light, etc.
  skin: auto

  # Hide the RSS/Atom feed icon in your social links
  hide_site_feed_link: false
